name: categora
description: Add a category, add items to the category, check off when done.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  #Firebase
  cloud_firestore: ^1.0.7
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0

  #Toasts
  fluttertoast: ^8.0.6

  #State Management
  stacked: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  fonts:
        - family: Pacifico
          fonts:
              - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
                weight: 400
              - asset: assets/fonts/Pacifico/Pacifico-Light.ttf
                weight: 300

        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
                weight: 300
              - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
                weight: 300
                style: italic
              - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
                weight: 400
              - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
                weight: 500
              - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
                weight: 600
